stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/
    - .npm/

build-job:
  stage: build
  image: node:latest
  script:
    - yarn
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

lint-job:
  stage: test
  image: node:latest
  script:
    - yarn lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
