stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/
    - .npm/

build-job:
  stage: build
  image: npm:latest
  script:
    - npm install
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

unit-test-job:
  stage: test
  image: npm:latest
  script:
    - npm test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
