name: pipeline-workflow

on:
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Run the pipeline YAML file based on event data
      - run: |
          echo "Unit test !"

